# Generated by Django 5.0.6 on 2024-06-21 00:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('strength_and_conditioning', 'Strength & Conditioning'), ('nutrition', 'Nutrition'), ('mental', 'Mental'), ('other', 'Other')], default='other', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('reading_time', models.IntegerField(choices=[(5, '5 mins'), (10, '10 mins'), (15, '15 mins'), (20, '20 mins')], default=5)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
