# Generated by Django 5.0.6 on 2024-07-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='bench',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='broad_jump',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='bronco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='chin_up',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='deadlift',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='forty_meter_sprint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='squat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='vertical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
