# Generated by Django 5.0.6 on 2024-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_trainer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a trainer.', verbose_name='Trainer status'),
        ),
    ]
