# Generated by Django 5.0.6 on 2024-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/'),
        ),
    ]
