# Generated by Django 5.0.6 on 2024-07-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='members/images/default_avatar.jpg', null=True, upload_to='profiles/avatars/'),
        ),
    ]
