# Generated by Django 5.0.6 on 2024-06-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HPost',
            new_name='Post',
        ),
    ]
