# Generated by Django 5.0.6 on 2024-07-05 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthclient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthClient',
            new_name='Client',
        ),
    ]
