# Generated by Django 5.0.6 on 2024-07-12 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_movement_exercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('squat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bench', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('chin_up', models.IntegerField(blank=True, null=True)),
                ('deadlift', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bronco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('broad_jump', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vertical', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('forty_meter_sprint', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
