# Generated by Django 5.0.6 on 2024-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_healthprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='bronco',
            field=models.CharField(blank=True, help_text='Enter duration in HH:MM format', max_length=8, null=True),
        ),
    ]
