# Generated by Django 5.0.6 on 2024-07-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_remove_plan_content_plan_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='health.plan'),
        ),
    ]
