# Generated by Django 5.0.6 on 2024-07-23 17:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Text'),
        ),
    ]
