# Generated by Django 5.0.6 on 2024-07-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_remove_exercise_movement_remove_exercise_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='health/plans/document/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='health/plans/covers/'),
        ),
    ]
