# Generated by Django 5.0.6 on 2024-05-28 13:09

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detailed_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Text')),
                ('event_type', models.CharField(choices=[('camp', 'Camp'), ('game', 'Game'), ('training', 'Training'), ('clinic', 'Clinic'), ('tournament', 'Tournament'), ('combine', 'Combine'), ('other', 'Other')], max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('registration_required', models.BooleanField(default=False)),
                ('payment_required', models.BooleanField(default=False)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_secondary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('spectator', 'Spectator')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
