# Generated by Django 5.0.6 on 2024-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='internal_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
    ]
