# Generated by Django 5.0.6 on 2024-06-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_rsvp_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.eventrole'),
        ),
    ]
