# Generated by Django 5.0.6 on 2024-05-24 15:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detailed_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Text'),
        ),
    ]
