# Generated by Django 5.0.6 on 2024-05-24 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
