# Generated by Django 5.0.6 on 2024-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_add_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
