# Generated by Django 5.0.6 on 2024-05-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rsvp_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost_secondary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
    ]
