name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.3'

    - name: Create and activate virtual environment, install dependencies, and collect static files
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

    - name: Pull latest changes on production server and deploy
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: f5local
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << 'EOF'
          # Navigate to the application directory
          cd /var/www/f5

          # Reset, clean, and pull the latest changes
          git reset --hard
          git clean -fd
          git pull origin main

          # Activate virtual environment
          source venv/bin/activate

          # Ensure the static files directory is writable
          sudo chown -R $SSH_USERNAME:www-data /var/www/f5/app/staticfiles

          pip install -r requirements.txt
          cd app/
          set -a  # Automatically export all variables
          source ../.env  # Source the .env file
          set +a

          # Collect static files and run migrations
          python manage.py collectstatic --noinput
          python manage.py migrate

          # Restart services
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx

          # Clean up
          rm -f private_key
        EOF